//$file${../src::main.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: rma.qm
// File:  ${../src::main.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../src::main.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"

typedef struct {
    QEvt super;
    uint32_t ticks;
    uint32_t iter;
} BlinkyPatternEvt;

uint32_t g_ticks = 1U;
uint32_t g_iter = 1500U;

//$declare${AOs::Blinky1} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky1} ............................................................
typedef struct {
// protected:
    QActive super;

// private:
    QTimeEvt te;

    uint32_t iter;
} Blinky1;

// public:
static void Blinky1_ctor(Blinky1 * const me);

// protected:
static QState Blinky1_initial(Blinky1 * const me, void const * const par);
static QState Blinky1_active(Blinky1 * const me, QEvt const * const e);
//$enddecl${AOs::Blinky1} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::Blinky2} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky2} ............................................................
typedef struct {
// protected:
    QActive super;

// private:
    QTimeEvt te;

    uint8_t seq;
} Blinky2;

// public:
static void Blinky2_ctor(Blinky2 * const me);

// protected:
static QState Blinky2_initial(Blinky2 * const me, void const * const par);
static QState Blinky2_active(Blinky2 * const me, QEvt const * const e);
//$enddecl${AOs::Blinky2} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Blinky1} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky1} ............................................................

//${AOs::Blinky1::ctor} ......................................................
static void Blinky1_ctor(Blinky1 * const me) {
    QActive_ctor(&me->super, (QStateHandler)&Blinky1_initial);
    QTimeEvt_ctorX(&me->te, &me->super, TIMEOUT_SIG, 0U);
}

//${AOs::Blinky1::SM} ........................................................
static QState Blinky1_initial(Blinky1 * const me, void const * const par) {
    //${AOs::Blinky1::SM::initial}
    QTimeEvt_armX(&me->te, 1U, 1U);
    me->iter = 1500U;

    QS_FUN_DICTIONARY(&Blinky1_active);

    return Q_TRAN(&Blinky1_active);
}

//${AOs::Blinky1::SM::active} ................................................
static QState Blinky1_active(Blinky1 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky1::SM::active::TIMEOUT}
        case BLINK_PATTERN_UPDATE_SIG:{
                QTimeEvt_disarm(&me->te);
                QTimeEvt_armX(&me->te, ((BlinkyPatternEvt const * )e)->ticks, ((BlinkyPatternEvt const* )e)->ticks);
                me->iter = ((BlinkyPatternEvt* )e)->iter;
                status_ = Q_HANDLED();
                break;
            }
        case TIMEOUT_SIG: {
            uint32_t volatile i = me->iter;
            for (;i != 0U;i--) {
                        BSP_greenLedOn();
                        BSP_greenLedOff();
                    }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky1} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Blinky2} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky2} ............................................................

//${AOs::Blinky2::ctor} ......................................................
static void Blinky2_ctor(Blinky2 * const me) {
    QActive_ctor(&me->super, (QStateHandler)&Blinky2_initial);
    QTimeEvt_ctorX(&me->te, &me->super, TIMEOUT_SIG, 0U);
}

//${AOs::Blinky2::SM} ........................................................
static QState Blinky2_initial(Blinky2 * const me, void const * const par) {
    //${AOs::Blinky2::SM::initial}

    QS_FUN_DICTIONARY(&Blinky2_active);
    me->seq = 0U;
    return Q_TRAN(&Blinky2_active);
}

//${AOs::Blinky2::SM::active} ................................................
static QState Blinky2_active(Blinky2 * const me, QEvt const * const e) {
    QState status_;
    enum {N_SEQ = 2};
    switch (e->sig) {
        //${AOs::Blinky2::SM::active::BUTTON_PRESSED}
        case BUTTON_PRESSED_SIG: {
            me->seq = (me->seq + 1U) % N_SEQ;
            static uint32_t const n_ticks[N_SEQ] = {2U, 1U};
            static uint32_t const n_iter[N_SEQ] = {3000U, 1500U};

            BlinkyPatternEvt *bp_evt = Q_NEW(BlinkyPatternEvt, BLINK_PATTERN_UPDATE_SIG);

            bp_evt->ticks = n_ticks[me->seq];
            for (uint32_t volatile i = 10 * 1500U;i != 0U;i--) {
                BSP_blueLedOn();
                BSP_blueLedOff();
            }
            bp_evt->iter = n_iter[me->seq];
            QACTIVE_POST(AO_Blinky1, &bp_evt->super, 0U);


            for (uint32_t volatile i = 1 * 1500U;i != 0U;i--) {
                        BSP_blueLedOn();
                        BSP_blueLedOff();
                    }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky2} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

static QEvt const *blinky1_queue[10];
static Blinky1 blinky1;

static QEvt const *blinky2_queue[10];
static Blinky2 blinky2;

static BlinkyPatternEvt evt_pool[10];

QActive* const AO_Blinky1 = &blinky1.super;
QActive* const AO_Blinky2 = &blinky2.super;

/* the main function =========================================================*/
int main() {
    BSP_init(); /* initialize the BSP */
    QF_init();   /* initialize QP/C */

    QF_poolInit(evt_pool, sizeof(evt_pool), sizeof(evt_pool[0]));

    Blinky1_ctor(&blinky1);
    QACTIVE_START(&blinky1,
        5U,
        blinky1_queue,
        sizeof(blinky1_queue)/ sizeof(blinky1_queue[0]),
        (void*)0, 0U,
        (void*)0
        );

    Blinky2_ctor(&blinky2);
    QACTIVE_START(&blinky2,
        2U,
        blinky2_queue,
        sizeof(blinky2_queue)/ sizeof(blinky2_queue[0]),
        (void*)0, 0U,
        (void*)0
        );

    QF_run(); /* run QP/C */
    return 0; /* NOTE: the scheduler does NOT return */
}

